services:

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-extensions:/opt/sonarqube/extensions
      - sonarqube-logs:/opt/sonarqube/logs
    restart: unless-stopped

  nexus:
    image: sonatype/nexus3:3.86.2
    container_name: nexus
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data
    restart: unless-stopped

  trivy:
    image: aquasec/trivy:0.72.0
    container_name: trivy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - trivy-cache:/root/.cache/trivy
    entrypoint: ["trivy"]
    command: ["--version"]

volumes:
  sonarqube-data:
  sonarqube-extensions:
  sonarqube-logs:
  nexus-data:
  trivy-cache: