spring.application.name=twitter-app

spring.datasource.url=jdbc:mysql://8.231.118.207:3306/twitterdb?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=twitteruser
spring.datasource.password=admin12345

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

spring.thymeleaf.cache=false

# Actuator Health Endpoint
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true

